apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.back_one.metadata.name }}-config
  namespace: {{ .Values.back_one.metadata.namespace }}
{{- if .Values.back_one.configmapData }}
data:
{{-  range $configmapKey, $configmapValue := .Values.back_one.configmapData }}
  {{ $configmapKey }}: {{ toYaml $configmapValue | quote }}
{{- end }}
{{- end }}

