{{- if .Values.back_one.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.back_one.metadata.name }}
  namespace: {{ .Values.back_one.metadata.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.back_one.metadata.name }}
  minReplicas: {{ .Values.back_one.autoscaling.minReplicas}}
  maxReplicas: {{ .Values.back_one.autoscaling.maxReplicas}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.back_one.autoscaling.targetCPUUtilizationPercentage}}
{{- end}}