apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.service.name }}
  namespace: {{ .Values.mongo.metadata.namespace }}
spec:
  selector:
    app: {{ .Values.mongo.metadata.name }}
  ports:
  - port: {{ .Values.mongo.service.port }}
    targetPort: {{ .Values.mongo.service.targetPort }}
  clusterIP: {{ .Values.mongo.service.clusterIP }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongo.metadata.name }}
  namespace: {{ .Values.mongo.metadata.namespace }}
spec:
  serviceName: {{ .Values.mongo.service.name }}
  selector:
    matchLabels:
      app: {{ .Values.mongo.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.metadata.name }}
    spec:
      containers:
      - name: mongo-deployment
        image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
        imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: {{ .Values.mongo.service.port }}
        volumeMounts:
        - mountPath: {{ .Values.mongo.volume.mountPath }}
          name: {{ .Values.mongo.volume.name }}
      volumes:
        - name: {{ .Values.mongo.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.mongo.volume.ClaimName }}
        

