{{- $configmap := print .Values.back_two.metadata.name "-config" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.back_one.metadata.name }}
  namespace: {{ .Values.back_one.metadata.namespace }}
  labels:
    app: {{ .Values.back_one.metadata.name }}
spec:
  replicas: {{ .Values.back_one.spec.replicasCout }}
{{- if .Values.back_one.spec.strategy }}
  strategy:
{{ toYaml .Values.back_one.spec.strategy | indent 4 }}
{{- end}}
  selector:
    matchLabels:
      app: {{ .Values.back_one.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.back_one.metadata.name }}
    spec:
      containers:
      - name: {{ .Values.back_one.metadata.name }}
        image: {{ .Values.back_one.image.repository }}:{{ .Values.back_one.image.tag }}
        imagePullPolicy: {{ .Values.back_one.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.back_one.service.port }}
        {{- if .Values.back_one.spec.containers.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.back_one.spec.containers.readinessProbe | indent 10 }}
        {{- end}}
        {{- if .Values.back_one.spec.containers.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.back_one.spec.containers.livenessProbe | indent 10 }}           
        {{- end}}
{{- if .Values.back_one.spec.containers.resources }}
        resources:
{{ toYaml .Values.back_one.spec.containers.resources | indent 10 }}
{{- end}}
        env:
{{-  range $configmapKey, $configmapValue := .Values.back_one.configmapData }}
          - name: {{ $configmapKey }}
            valueFrom:
              configMapKeyRef:
                name: {{$configmap}}
                key: {{ $configmapKey }}
{{- end}}
