kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-claim
  namespace: testing
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi